### ISSUE TITLE
Memory shooting up when exception DEADLINE_EXCEEDED: Deadline expired before operation could complete.

### ISSUE THREAD

**Issue by sunils2020** [googleapis/sdk-platform-java#1333]
We are trying to post metrics to Google stack driver. We started noticing many exceptions around 3:15 PM IST  
The code used to work fine but it off late we see lot of Deadline exceeded exceptions. While this happens, We are noticing memory shooting up and potentially bringing down the system. 

Is there any reason why memory is not released when this exception occurs?

```
ec 15 15:28:35 ip-10-1-6-159 server: com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Deadline expired before operation could complete.
Dec 15 15:28:35 ip-10-1-6-159 server: at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:94)
Dec 15 15:28:35 ip-10-1-6-159 server: at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
Dec 15 15:28:35 ip-10-1-6-159 server: at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
Dec 15 15:28:35 ip-10-1-6-159 server: at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
Dec 15 15:28:35 ip-10-1-6-159 server: at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
Dec 15 15:28:35 ip-10-1-6-159 server: at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
Dec 15 15:28:35 ip-10-1-6-159 server: at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
Dec 15 15:28:35 ip-10-1-6-159 server: at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
Dec 15 15:28:35 ip-10-1-6-159 server: at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
Dec 15 15:28:35 ip-10-1-6-159 server: at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
Dec 15 15:28:35 ip-10-1-6-159 server: at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
Dec 15 15:28:35 ip-10-1-6-159 server: at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:572)
Dec 15 15:28:35 ip-10-1-6-159 server: at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:542)
Dec 15 15:28:35 ip-10-1-6-159 server: at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
Dec 15 15:28:35 ip-10-1-6-159 server: at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
Dec 15 15:28:35 ip-10-1-6-159 server: at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
Dec 15 15:28:35 ip-10-1-6-159 server: at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:535)
Dec 15 15:28:35 ip-10-1-6-159 server: at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
Dec 15 15:28:35 ip-10-1-6-159 server: at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
Dec 15 15:28:35 ip-10-1-6-159 server: at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
Dec 15 15:28:35 ip-10-1-6-159 server: at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
Dec 15 15:28:35 ip-10-1-6-159 server: at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
```

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

#### Environment details

  - Programming language: Java
  - OS: Amazon Linux 2
  - Language runtime version:8.5 Amazon Corretto
  - Package version: 3.3.0
  - 		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-monitoring</artifactId>
			<version>3.3.0</version>
		</dependency>

#### Steps to reproduce

 This doesn't occur always

**Comment by JoeWang1127** [comment]
Hi @sunils2020, do you still have this issue?

**Comment by JoeWang1127** [comment]
Close as no respond from customer, reopen if needed.
