### ISSUE TITLE
showcase: sonarcloud build on main fails with errors from cleanQueue for ManagedChannel 

### ISSUE THREAD

**Issue by emmileaf** [googleapis/sdk-platform-java#1744]
```
[INFO] Running com.google.showcase.v1beta1.it.ITLongRunningOperation
Jun 05, 2023 3:37:57 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Previous channel ManagedChannelImpl{logId=21, target=localhost:7469} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:102)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:60)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:51)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:631)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:391)
	at com.google.api.gax.grpc.ChannelPool.<init>(ChannelPool.java:107)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:85)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:237)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:231)
...
Jun 05, 2023 3:37:57 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Previous channel ManagedChannelImpl{logId=29, target=localhost:7469} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
...
Jun 05, 2023 3:37:57 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Previous channel ManagedChannelImpl{logId=23, target=localhost:7469} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
...
Jun 05, 2023 3:37:57 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Previous channel ManagedChannelImpl{logId=25, target=localhost:7469} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site

```
```
Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 23.148 s <<< FAILURE! - in com.google.showcase.v1beta1.it.ITLongRunningOperation
Error:  com.google.showcase.v1beta1.it.ITLongRunningOperation.testGRPC_LROUnsuccessfulResponse_exceedsTotalTimeout_throwsDeadlineExceededException  Time elapsed: 7.662 s  <<< FAILURE!
java.lang.AssertionError: expected java.util.concurrent.CancellationException to be thrown, but nothing was thrown
	at org.junit.Assert.assertThrows(Assert.java:1028)
	at org.junit.Assert.assertThrows(Assert.java:981)
	at com.google.showcase.v1beta1.it.ITLongRunningOperation.testGRPC_LROUnsuccessfulResponse_exceedsTotalTimeout_throwsDeadlineExceededException(ITLongRunningOperation.java:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by lqiu96** [comment]
I believe this is a known issue: https://github.com/googleapis/sdk-platform-java/issues/1680

I'm working on https://github.com/googleapis/sdk-platform-java/pull/1669 which should try and resolve these issues.

**Comment by emmileaf** [comment]
My bad, missed that this was already being tracked. Closing this - thanks @lqiu96!
