### ISSUE TITLE
gax-java(windows, mac): NoSuchMethodError on com.google.api.gax.core.InstantiatingExecutorProvider.newIOBuilder()

### ISSUE THREAD

**Issue by emmileaf** [googleapis/sdk-platform-java#1745]
Example log: https://github.com/googleapis/sdk-platform-java/actions/runs/5179277502/jobs/9332413932

Stack trace:
```
[INFO] Running com.google.api.gax.httpjson.longrunning.OperationsClientTest
Error:  Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.003 s <<< FAILURE! - in com.google.api.gax.httpjson.longrunning.OperationsClientTest
Error:  com.google.api.gax.httpjson.longrunning.OperationsClientTest  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NoSuchMethodError: com.google.api.gax.core.InstantiatingExecutorProvider.newIOBuilder()Lcom/google/api/gax/core/InstantiatingExecutorProvider$Builder;
	at com.google.api.gax.httpjson.ManagedHttpJsonChannel$Builder.build(ManagedHttpJsonChannel.java:222)
	at com.google.api.gax.httpjson.InstantiatingHttpJsonChannelProvider.createChannel(InstantiatingHttpJsonChannelProvider.java:196)
	at com.google.api.gax.httpjson.InstantiatingHttpJsonChannelProvider.getTransportChannel(InstantiatingHttpJsonChannelProvider.java:155)
	at com.google.api.gax.httpjson.InstantiatingHttpJsonChannelProvider.getTransportChannel(InstantiatingHttpJsonChannelProvider.java:62)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:201)
	at com.google.api.gax.httpjson.longrunning.stub.HttpJsonOperationsStub.create(HttpJsonOperationsStub.java:205)
	at com.google.api.gax.httpjson.longrunning.stub.OperationsStubSettings.createStub(OperationsStubSettings.java:193)
	at com.google.api.gax.httpjson.longrunning.OperationsClient.<init>(OperationsClient.java:163)
	at com.google.api.gax.httpjson.longrunning.OperationsClient.create(OperationsClient.java:138)
	at com.google.api.gax.httpjson.longrunning.OperationsClientTest.startStaticServer(OperationsClientTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

Error:  com.google.api.gax.httpjson.longrunning.OperationsClientTest  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NullPointerException
	at com.google.api.gax.httpjson.longrunning.OperationsClientTest.stopServer(OperationsClientTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
```

**Comment by emmileaf** [comment]
Possibly relevant location and change: 
`executor = InstantiatingExecutorProvider.newIOBuilder().build().getExecutor()` ([ManagedHttpJsonChannel](https://github.com/googleapis/sdk-platform-java/blame/dea8426a85b53d08d3c8d317a1af4312889b1a3d/gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ManagedHttpJsonChannel.java#L222 )) as part of #1677

**Comment by lqiu96** [comment]
I wonder if this is due to the cache as part of the setup-java step in the CI? Might have cached the old gax version. I'm going to try and clean up the cache and see if that resolves some of the nightly issues. Might just be a transient issue then.

**Comment by lqiu96** [comment]
I deleted the old caches used in the setup-java set and re-ran the nightlies: https://github.com/googleapis/sdk-platform-java/actions/runs/5179277502/jobs/9333861619 

I think they should be fine now and this probably is just a transient issue. I think it should be fine
