### ISSUE TITLE
Generator emits duplicate entry error when generating from `google/iam/v1`

### ISSUE THREAD

**Issue by JoeWang1127** [googleapis/sdk-platform-java#1992]
When generate library from `google/iam/v1`, the generator emits an error:
```
Exception in thread "main" com.google.api.generator.gapic.protowriter.Writer$GapicWriterException: Could not write code for class com.google.iam.v1.stub.IAMPolicyStub: duplicate entry: src/main/java/com/google/iam/v1/stub/IAMPolicyStub.java
        at com.google.api.generator.gapic.protowriter.Writer.writeClazz(Writer.java:137)
        at com.google.api.generator.gapic.protowriter.Writer.write(Writer.java:68)
        at com.google.api.generator.gapic.Generator.generateGapic(Generator.java:35)
        at com.google.api.generator.Main.main(Main.java:28)
Caused by: java.util.zip.ZipException: duplicate entry: src/main/java/com/google/iam/v1/stub/IAMPolicyStub.java
        at java.base/java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:244)
        at java.base/java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:115)
        at com.google.api.generator.gapic.protowriter.Writer.writeClazz(Writer.java:133)
        ... 3 more
```

**Comment by blakeli0** [comment]
Can I get more info about it? Does it happen only when triggering from the shell script?

**Comment by JoeWang1127** [comment]
> Can I get more info about it? Does it happen only when triggering from the shell script?

Yes, this is a bug in the shell script: if we pass two identical protos () to the generator, it will exit with the above error. I think the shell script or the generator should try to deduplicate the protos.

That being said, `google/iam/v1` should not be generated in the first place because it doesn't have a `java_gapic_library` target. Do you know why this library is chosen as one of the [goldens](https://github.com/googleapis/sdk-platform-java/tree/main/test/integration/goldens/iam)? The libraries in `google-cloud-java` are from `google/iam/admin/v1` and `google/iam/v2`.

**Comment by blakeli0** [comment]
I see, this is one more edge case we have to handle in the script. [java-iam](https://github.com/googleapis/sdk-platform-java/tree/main/java-iam) is a module of sdk-platform-java. It indeed does not have `java_gapic_library`, but it should be generated with grpc and proto folders, as iam is a common feature that used by other services.

**Comment by JoeWang1127** [comment]
Sure, I will address this issue as the next step.
