### ISSUE TITLE
ITHttpAnnotation test fails with HttpResponseException in JDK 21

### ISSUE THREAD

**Issue by mpeddada1** [googleapis/sdk-platform-java#2695]
Discovered in https://github.com/googleapis/sdk-platform-java/pull/2694. The ITHttpAnnotationTest fails with the following error:

```
Error:  Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.072 s <<< FAILURE! -- in com.google.showcase.v1beta1.it.ITHttpAnnotation
Error:  com.google.showcase.v1beta1.it.ITHttpAnnotation.testComplianceGroup[Compliance Group Name: Fully working conversions, no resources] -- Time elapsed: 0.014 s <<< ERROR!
com.google.api.gax.rpc.InvalidArgumentException: Bad Request
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:52)
	at com.google.api.gax.httpjson.HttpJsonApiExceptionFactory.createApiException(HttpJsonApiExceptionFactory.java:76)
	at com.google.api.gax.httpjson.HttpJsonApiExceptionFactory.create(HttpJsonApiExceptionFactory.java:54)
	at 

. . .
Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
POST http://localhost:7469/v1beta1/repeat:body
{"error":{"code":400,"message":"error reading body params '*': proto: syntax error (line 1:513): invalid value \u0000","details":null,"Body":"","Header":null,"Errors":null}}
	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
	at com.google.api.gax.httpjson.HttpRequestRunnable.run(HttpRequestRunnable.java:115)
	... 6 more
```

Note that this test doesn't fail consistently. Running the same test 20 times shows the test failing 15/20 times.
<img width="1747" alt="Screenshot 2024-04-25 at 6 29 20 PM" src="https://github.com/googleapis/sdk-platform-java/assets/66699525/e8fdbcb1-d432-4964-a07d-94f7e420ad2f">

The exception is being thrown at [HttpRequest#execute](https://github.com/googleapis/google-http-java-client/blob/7f58bd58e49cb823cf84c4efea99c43f0234f54f/google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java#L1114-L1123).

**Comment by lqiu96** [comment]
We have a suspicion that it is an issue in the showcase server: https://github.com/googleapis/gapic-showcase/issues/1519
